### ISSUE TITLE
Final doc & readme polishing

### ISSUE THREAD

**Issue by vdusek** [apify/crawlee-python#266]
These items are currently blocked but should be resolved before the public launch (8. 7.).

### TODO

- [x] Replace all occurrences of `apify.github.io/crawlee-python` with `crawlee.dev/python` in `README.md` once the redirect works.
- [x] Link the API documentation to appropriate sections in `README.md` once API doc is ready.
- [x] Link the API documentation in the Quick Start, Introduction, and Examples sections of the documentation once API doc is ready.
- [x] Please review `README.md` and do final updates if necessary.
- [x] Fix features on homepage (which is now just a copy of the JS homepage including its features)
- [x] Context-aware search (JS version only searches JS content and python version only python content)
